### ISSUE TITLE
The provided example boards.yml configuration doesn't work because of missing ingress paths

### ISSUE THREAD

**Issue by DMW007** [isw-kudos/kudos-docs#12]
The [example `boards.yml` var file for the helm chart](https://docs.huddo.com/boards/kubernetes/#update-config-file) doesn't work. After deploying, the application shows only a white screen and all client requests leads into 404 errors:

![VirtualBoxVM_2021-07-06_22-51-01](https://user-images.githubusercontent.com/21245043/124665243-c5405180-deac-11eb-80d4-8436d60b69ad.png)

I could reproduce this on a vanilla cluster. After checking the configuration, I found out that this cannot work since both ingress instances (frontend + api) are using the same root path, which is not specified in the annotations (resulting in the default of `/`):

```bash
$ kging
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME              CLASS    HOSTS                             ADDRESS                    PORTS   AGE
boards-core       <none>   boards.cnx65-k8s.hobel.internal   cnx65-k8s.hobel.internal   80      29m
boards-webfront   <none>   boards.cnx65-k8s.hobel.internal   cnx65-k8s.hobel.internal   80      29m
$ kding boards-core
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             boards-core
Namespace:        boards
Address:          cnx65-k8s.hobel.internal
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                             Path  Backends
  ----                             ----  --------
  boards.cnx65-k8s.hobel.internal  
                                   /   boards-core:http (10.42.0.10:3001,10.42.0.18:3001)
Annotations:                       meta.helm.sh/release-name: boards
                                   meta.helm.sh/release-namespace: boards
                                   nginx.ingress.kubernetes.io/affinity: cookie
                                   nginx.ingress.kubernetes.io/proxy-body-size: 50m
                                   nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
                                   nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  CREATE  29m   nginx-ingress-controller  Ingress boards/boards-core
  Normal  UPDATE  29m   nginx-ingress-controller  Ingress boards/boards-core
$ kding boards-webfront
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             boards-webfront
Namespace:        boards
Address:          cnx65-k8s.hobel.internal
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                             Path  Backends
  ----                             ----  --------
  boards.cnx65-k8s.hobel.internal  
                                   /   boards-webfront:http (10.42.0.11:8080,10.42.0.16:8080)
Annotations:                       meta.helm.sh/release-name: boards
                                   meta.helm.sh/release-namespace: boards
Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  CREATE  29m   nginx-ingress-controller  Ingress boards/boards-webfront
  Normal  UPDATE  29m   nginx-ingress-controller  Ingress boards/boards-webfront
```

This seems wrong since the default config expects the UI in `/boards` and it's api in `/boards-api`, so I changed the ingress definition to match those paths:

```yaml
webfront:
  image:
    tag: webfront
  env:
    API_GATEWAY: 'http://boards.cnx65-k8s.hobel.internal/api-boards'
  ingress:
    hosts:
      - 'boards.cnx65-k8s.hobel.internal'
    path: /boards/?(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1

core:
  image:
    tag: core
  env:
    API_URI_PATH: /api-boards
    # NODE_TLS_REJECT_UNAUTHORIZED: "0"
  ingress:
    hosts:
      - 'boards.cnx65-k8s.hobel.internal'
    path: /api-boards/?(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
```
Now the UI is shown and all requests were completed successfully:

![VirtualBoxVM_2021-07-06_23-30-25](https://user-images.githubusercontent.com/21245043/124669124-2a4a7600-deb2-11eb-8d4f-b62442a334cd.png)

This should be listed as example, since imho the configuration without any path can't work. 

### Kubernetes

```bash
$ kgnoowide
NAME                       STATUS   ROLES                      AGE   VERSION    INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
cnx65-k8s.hobel.internal   Ready    controlplane,etcd,worker   40m   v1.19.12   192.168.10.136   <none>        CentOS Linux 7 (Core)   3.10.0-1127.el7.x86_64   docker://20.10.7

$ kex nginx-ingress-controller-6nkt5 -n ingress-nginx -- /nginx-ingress-controller --version
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       nginx-0.35.0-rancher2
  Build:         git-ba9a25e23
  Repository:    https://github.com/rancher/ingress-nginx.git
  nginx version: nginx/1.19.2

-------------------------------------------------------------------------------
```
The full configuration file from your example repo which I used before applying any modifications on the ingress:
```yaml
$ cat /tmp/boards-parsed.yml 
global:
  # repository: iswkudos/kudos-boards-docker DEPRECRATED AS OF 2019-10-16 RELEASE
  repository: iswkudos/kudos-boards
  # Uncomment the next line to lock your deployment to a specific release date (YYYY-MM-DD)
  imageTagSuffix: '2021-06-02'
  # Uncomment the following line if you are using a legacy version of Kube (ie <= 1.13)
  # legacyKube: true
  env:
    APP_URI: 'http://boards.cnx65-k8s.hobel.internal/boards'
    APP_URI_PATH: '/boards'
    # MONGO_USER: admin
    # MONGO_PASSWORD: password
    MONGO_HOST: mongo-service:27017
    MONGO_PARAMS: replicaSet=replicaset
    S3_ENDPOINT: minio-service
    S3_ACCESS_KEY: 'myAccessKey'
    S3_SECRET_KEY: 'mySecret'
    S3_BUCKET: huddo-boards

licence:
  env:
    # Register your Organisation and download your Free 'Activities Plus' licence key from store.huddo.com
    LICENCE: 'xxx'

webfront:
  image:
    tag: webfront
  env:
    API_GATEWAY: 'http://boards.cnx65-k8s.hobel.internal/api-boards'
    # DOCUMENTATION_URL: https://docs.huddo.com/boards/howto/knowledgebase/
    # PRODUCT_INFO_URL: https://huddo.com/boards
    # SUPPORT_EMAIL: support@example.com
  ingress:
    hosts:
      - 'boards.cnx65-k8s.hobel.internal'

events:
  image:
    tag: boards-event
  env:
    NOTIFIER_EMAIL_HOST: smtp.example.com
    # NOTIFIER_EMAIL_USERNAME: username
    # NOTIFIER_EMAIL_PASSWORD: password
    # NOTIFIER_EMAIL_PORT: 25
    # NODE_TLS_REJECT_UNAUTHORIZED: "0"

core:
  image:
    tag: core
  env:
    API_URI_PATH: /api-boards
    # NODE_TLS_REJECT_UNAUTHORIZED: "0"
  ingress:
    hosts:
      - 'boards.cnx65-k8s.hobel.internal'
      
app:
  image:
    tag: boards

provider:
  env:
    #NODE_TLS_REJECT_UNAUTHORIZED: "0"
    WIDGET_ID: Huddo Community Boards
    # https://docs.huddo.com/boards/msgraph/teams-on-prem/
    # Uncomment/configure the following line if you are using this Huddo Boards deployment from Microsoft Teams
    # MSGRAPH_TEAMS_APP_ID: app-id-shown-in-teams-url

user:
  env:
    # NODE_TLS_REJECT_UNAUTHORIZED: "0"
    # DISABLE_WELCOME_EMAIL: false
    CONNECTIONS_NAME: Connections
    CONNECTIONS_CLIENT_ID: 'huddoboards4'
    # Fetched using boards-was role
    CONNECTIONS_CLIENT_SECRET: 'x'
    CONNECTIONS_ADMINS: "[\"max.muster@example.com\"]"
    CONNECTIONS_URL: 'https://cnx65.hobel.internal'
```
