### ISSUE TITLE
MongoDB and Minio can't be deployed because removed api versions are used

### ISSUE THREAD

**Issue by DMW007** [isw-kudos/kudos-docs#13]
The [example yaml files in the MongoDB documentation](https://docs.huddo.com/boards/kubernetes/mongo/) can't be deployed, since the used [v1beta API version got removed](https://www.pulumi.com/docs/reference/pkg/kubernetes/apps/v1beta1/deployment/) already since kubernetes v1.16:

```
$ ka mongo.yaml
persistentvolume/kudos-mongo created
persistentvolumeclaim/kudos-mongo-claim created
service/mongo-service created
error: unable to recognize "mongo.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
```
So the API version should be replaced by the current `apps/v1` one. This also requires to specify `spec.selector.matchLabels` like this:

```yaml
kind: Deployment
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
metadata:
  name: mongo
  namespace: boards
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: mongo
          image: bitnami/mongodb:4.4
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512M
          ports:
            - containerPort: 27017
          env:
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: mongo-service
          volumeMounts:
          - mountPath: /bitnami
            name: mongo-vol
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: kudos-mongo-claim
```
Now the deployment can be created:
```bash
$ ka mongo.yaml
persistentvolume/kudos-mongo unchanged
persistentvolumeclaim/kudos-mongo-claim unchanged
deployment.apps/mongo created
service/mongo-service unchanged
```
Both MongoDB and Monio yaml files from your example repo are affected by this removed API issue.

Verified on kubernetes v1.19.12 and v1.20.8.
